In [239]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px



pd.set_option('display.float_format', '{:.2f}'.format)

In [241]:
wine = fetch_ucirepo(id=186)

ConnectionError: Error connecting to server

In [ ]:
wine

{'data': {'ids': None,
  'features':       fixed_acidity  volatile_acidity  citric_acid  ...    pH  sulphates  alcohol
  0               7.4              0.70         0.00  ...  3.51       0.56      9.4
  1               7.8              0.88         0.00  ...  3.20       0.68      9.8
  2               7.8              0.76         0.04  ...  3.26       0.65      9.8
  3              11.2              0.28         0.56  ...  3.16       0.58      9.8
  4               7.4              0.70         0.00  ...  3.51       0.56      9.4
  ...             ...               ...          ...  ...   ...        ...      ...
  6492            6.2              0.21         0.29  ...  3.27       0.50     11.2
  6493            6.6              0.32         0.36  ...  3.15       0.46      9.6
  6494            6.5              0.24         0.19  ...  2.99       0.46      9.4
  6495            5.5              0.29         0.30  ...  3.34       0.38     12.8
  6496            6.0              0.21         0.38  ...  3.26       0.32     11.8

  [6497 rows x 11 columns],
  'targets':       quality
  0           5
  1           5
  2           5
  3           6
  4           5
  ...       ...
  6492        6
  6493        5
  6494        6
  6495        7
  6496        6

  [6497 rows x 1 columns],
  'original':       fixed_acidity  volatile_acidity  citric_acid  ...  alcohol  quality  color
  0               7.4              0.70         0.00  ...      9.4        5    red
  1               7.8              0.88         0.00  ...      9.8        5    red
  2               7.8              0.76         0.04  ...      9.8        5    red
  3              11.2              0.28         0.56  ...      9.8        6    red
  4               7.4              0.70         0.00  ...      9.4        5    red
  ...             ...               ...          ...  ...      ...      ...    ...
  6492            6.2              0.21         0.29  ...     11.2        6  white
  6493            6.6              0.32         0.36  ...      9.6        5  white
  6494            6.5              0.24         0.19  ...      9.4        6  white
  6495            5.5              0.29         0.30  ...     12.8        7  white
  6496            6.0              0.21         0.38  ...     11.8        6  white

  [6497 rows x 13 columns],
  'headers': Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
         'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
         'pH', 'sulphates', 'alcohol', 'quality', 'color'],
        dtype='str')},
 'metadata': {'uci_id': 186,
  'name': 'Wine Quality',
  'repository_url': 'https://archive.ics.uci.edu/dataset/186/wine+quality',
  'data_url': 'https://archive.ics.uci.edu/static/public/186/data.csv',
  'abstract': 'Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).',
  'area': 'Business',
  'tasks': ['Classification', 'Regression'],
  'characteristics': ['Multivariate'],
  'num_instances': 4898,
  'num_features': 11,
  'feature_types': ['Real'],
  'demographics': [],
  'target_col': ['quality'],
  'index_col': None,
  'has_missing_values': 'no',
  'missing_values_symbol': None,
  'year_of_dataset_creation': 2009,
  'last_updated': 'Wed Nov 15 2023',
  'dataset_doi': '10.24432/C56S3T',
  'creators': ['Paulo Cortez',
   'A. Cerdeira',
   'F. Almeida',
   'T. Matos',
   'J. Reis'],
  'intro_paper': {'ID': 252,
   'type': 'NATIVE',
   'title': 'Modeling wine preferences by data mining from physicochemical properties',
   'authors': 'P. Cortez, A. Cerdeira, Fernando Almeida, Telmo Matos, J. Reis',
   'venue': 'Decision Support Systems',
   'year': 2009,
   'journal': None,
   'DOI': None,
   'URL': 'https://www.semanticscholar.org/paper/Modeling-wine-preferences-by-data-mining-from-Cortez-Cerdeira/bf15a0ccc14ac1deb5cea570c870389c16be019c',
   'sha': None,
   'corpus': None,
   'arxiv': None,
   'mag': None,
   'acl': None,
   'pmid': None,
   'pmcid': None},
  'additional_info': {'summary': 'The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine. For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].  Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).\n\nThese datasets can be viewed as classification or regression tasks.  The classes are ordered and not balanced (e.g. there are many more normal wines than excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent or poor wines. Also, we are not sure if all input variables are relevant. So it could be interesting to test feature selection methods.\n',
   'purpose': None,
   'funded_by': None,
   'instances_represent': None,
   'recommended_data_splits': None,
   'sensitive_data': None,
   'preprocessing_description': None,
   'variable_info': 'For more information, read [Cortez et al., 2009].\r\nInput variables (based on physicochemical tests):\r\n   1 - fixed acidity\r\n   2 - volatile acidity\r\n   3 - citric acid\r\n   4 - residual sugar\r\n   5 - chlorides\r\n   6 - free sulfur dioxide\r\n   7 - total sulfur dioxide\r\n   8 - density\r\n   9 - pH\r\n   10 - sulphates\r\n   11 - alcohol\r\nOutput variable (based on sensory data): \r\n   12 - quality (score between 0 and 10)',
   'citation': None}},
 'variables':                     name     role  ... units missing_values
 0          fixed_acidity  Feature  ...  None             no
 1       volatile_acidity  Feature  ...  None             no
 2            citric_acid  Feature  ...  None             no
 3         residual_sugar  Feature  ...  None             no
 4              chlorides  Feature  ...  None             no
 5    free_sulfur_dioxide  Feature  ...  None             no
 6   total_sulfur_dioxide  Feature  ...  None             no
 7                density  Feature  ...  None             no
 8                     pH  Feature  ...  None             no
 9              sulphates  Feature  ...  None             no
 10               alcohol  Feature  ...  None             no
 11               quality   Target  ...  None             no
 12                 color    Other  ...  None             no

 [13 rows x 7 columns]}

In [ ]:
type(wine)

ucimlrepo.dotdict.dotdict

In [ ]:
wine_df = pd.DataFrame.from_dict(wine.data.original)

wine_df.head(5)

   fixed_acidity  volatile_acidity  citric_acid  ...  alcohol  quality  color
0            7.4              0.70         0.00  ...      9.4        5    red
1            7.8              0.88         0.00  ...      9.8        5    red
2            7.8              0.76         0.04  ...      9.8        5    red
3           11.2              0.28         0.56  ...      9.8        6    red
4            7.4              0.70         0.00  ...      9.4        5    red

[5 rows x 13 columns]

In [ ]:
wine_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  color                 6497 non-null   str
dtypes: float64(11), int64(1), str(1)
memory usage: 660.0 KB

In [ ]:
(wine_df_summary := wine_df.describe())

       fixed_acidity  volatile_acidity  ...      alcohol      quality
count    6497.000000       6497.000000  ...  6497.000000  6497.000000
mean        7.215307          0.339666  ...    10.491801     5.818378
std         1.296434          0.164636  ...     1.192712     0.873255
min         3.800000          0.080000  ...     8.000000     3.000000
25%         6.400000          0.230000  ...     9.500000     5.000000
50%         7.000000          0.290000  ...    10.300000     6.000000
75%         7.700000          0.400000  ...    11.300000     6.000000
max        15.900000          1.580000  ...    14.900000     9.000000

[8 rows x 12 columns]

### Inspect Wine dataframe based on Wine color

In [ ]:
print(f'The \'color\' column of the wine dataframe contains {len(wine_colors:=list(wine_df['color'].unique()))} colors : {wine_colors}')

The 'color' column of the wine dataframe contains 2 colors : ['red', 'white']

#### Inspection of the Red wine collection

In [ ]:
red_wine_df = wine_df.query("color=='red'")

display(red_wine_df.head())

print(f'Red wine dataframe has the shape {red_wine_df.shape}')

print(f'''   
Empty Values ?
 The Red wine collection has {sum(red_wine_df.isna().sum())} missing values \n
Duplicate Values ? \n
    Total Duplicates:
      The Red wine collection has \'{(num_dup := red_wine_df.duplicated().sum())}\' duplicate values out of \'{(total_obs := red_wine_df. shape[0])}\' observations
      
    Distinct Duplicate Pattern:
      Exactly {((red_wine_duplicated := red_wine_df[red_wine_df.duplicated].value_counts().to_frame()['count'].apply(lambda x: x + 1)) > 1).sum()} distinct rows appear more than once in the Red wine collection
  
The most occuring entry appears {max(red_wine_duplicated)} times
      ''')

   fixed_acidity  volatile_acidity  citric_acid  ...  alcohol  quality  color
0            7.4              0.70         0.00  ...      9.4        5    red
1            7.8              0.88         0.00  ...      9.8        5    red
2            7.8              0.76         0.04  ...      9.8        5    red
3           11.2              0.28         0.56  ...      9.8        6    red
4            7.4              0.70         0.00  ...      9.4        5    red

[5 rows x 13 columns]

Red wine dataframe has the shape (1599, 13)

Empty Values ?
 The Red wine collection has 0 missing values

Duplicate Values ?

    Total Duplicates:
      The Red wine collection has '240' duplicate values out of '1599' observations

    Distinct Duplicate Pattern:
      Exactly 220 distinct rows appear more than once in the Red wine collection

The most occuring entry appears 4 times

#### Inspection of the White wine collection

In [ ]:
white_wine_df = wine_df.query("color=='white'")

display(white_wine_df.head())

print(f'White wine dataframe has the shape {white_wine_df.shape}')

print(f'''   
Empty Values ?
 The White wine collection has {sum(white_wine_df.isna().sum())} missing values \n
Duplicate Values ? \n
    Total Duplicates:
      The White wine collection has \'{(num_dup := white_wine_df.duplicated().sum())}\' duplicate values out of \'{(total_obs := white_wine_df. shape[0])}\' observations
      
    Distinct Duplicate Pattern:
      Exactly {((white_wine_duplicated := white_wine_df[white_wine_df.duplicated].value_counts().to_frame()['count'].apply(lambda x: x + 1)) > 1).sum()} distinct rows appear more than once in the white wine collection
  
The most occuring entry appears {max(white_wine_duplicated)} times
      ''')

      fixed_acidity  volatile_acidity  citric_acid  ...  alcohol  quality  color
1599            7.0              0.27         0.36  ...      8.8        6  white
1600            6.3              0.30         0.34  ...      9.5        6  white
1601            8.1              0.28         0.40  ...     10.1        6  white
1602            7.2              0.23         0.32  ...      9.9        6  white
1603            7.2              0.23         0.32  ...      9.9        6  white

[5 rows x 13 columns]

White wine dataframe has the shape (4898, 13)

Empty Values ?
 The White wine collection has 0 missing values

Duplicate Values ?

    Total Duplicates:
      The White wine collection has '937' duplicate values out of '4898' observations

    Distinct Duplicate Pattern:
      Exactly 772 distinct rows appear more than once in the white wine collection

The most occuring entry appears 8 times

### Wine Dataframe statistical exploration

In [ ]:
diff = wine_df_summary.loc['max'] - wine_df_summary.loc['75%']
condition = diff > wine_df_summary.loc['mean']
sus_columns = wine_df_summary.columns[condition].tolist()

sus_columns

['fixed_acidity',
 'volatile_acidity',
 'citric_acid',
 'residual_sugar',
 'chlorides',
 'free_sulfur_dioxide',
 'total_sulfur_dioxide',
 'sulphates']

In [ ]:
# for item, value in dict(wine_df_summary.loc['max']).items():
#     for item, upper_limit in dict(wine_df_summary.loc['75%']).items():
#         for item, mean_value in dict(wine_df_summary.loc['mean']).items():
#             if (value - upper_limit > mean_value):
#                 sus_columns.append(item)

In [ ]:
# Q3 = wine_df_summary.loc['75%', 'residual_sugar']
# Q1 = wine_df_summary.loc['25%', 'residual_sugar']

# IQR = Q3 - Q1


# print(f'Upper Limit: { Q3 + (1.5 * IQR)} \nLower Limit: { Q1 - (1.5 * IQR)}')

In [ ]:
for col in wine_df_summary.columns:
    Q1 = wine_df_summary.loc['25%', col]
    Q3 = wine_df_summary.loc['75%', col]
    
    IQR = Q3 - Q1
    
    wine_df_summary.loc['lower_fence', col] = Q1 - (1.5 * IQR)
    wine_df_summary.loc['upper_fence', col] = Q3 + (1.5 * IQR)
    
    bounded_obs = ~ (
        
        wine_df[col].between(
            
            wine_df_summary.loc['lower_fence', col], 
            wine_df_summary.loc['upper_fence', col]
            
            )
                     )
    
    wine_df_summary.loc['outliers', col] = bounded_obs.sum()

In [ ]:
wine_df_summary

             fixed_acidity  volatile_acidity  ...  alcohol  quality
count              6497.00           6497.00  ...  6497.00  6497.00
mean                  7.22              0.34  ...    10.49     5.82
std                   1.30              0.16  ...     1.19     0.87
min                   3.80              0.08  ...     8.00     3.00
25%                   6.40              0.23  ...     9.50     5.00
50%                   7.00              0.29  ...    10.30     6.00
75%                   7.70              0.40  ...    11.30     6.00
max                  15.90              1.58  ...    14.90     9.00
upper_fence           9.65              0.66  ...    14.00     7.50
lower_fence           4.45             -0.02  ...     6.80     3.50
outliers            357.00            377.00  ...     3.00   228.00

[11 rows x 12 columns]